-- ============================================================
-- v26d: Seed 64 Human-Design-Tore (I-Ging-Hexagramme)
-- ============================================================

INSERT INTO public.hd_meanings
  (category, key, title, emoji, keywords, short_text, sort_order)
VALUES
('gate','1','Selbst-Ausdruck','1️⃣',ARRAY['Kreativität','Inspiration','Rolle'],'Das kreative Selbst: dein einzigartiger Ausdruck.',1),
('gate','2','Richtung des Selbst','2️⃣',ARRAY['Empfang','Richtung','Führung'],'Die Empfängerin. Du kennst, wohin es geht.',2),
('gate','3','Ordnung','3️⃣',ARRAY['Anfang','Chaos','Mutation'],'Schwierigkeiten am Anfang. Ordnung aus Chaos.',3),
('gate','4','Formulierung','4️⃣',ARRAY['Antwort','Jugendliche Torheit','Logik'],'Antworten – wartet auf Fragen.',4),
('gate','5','Rhythmus','5️⃣',ARRAY['Muster','Routine','Warten'],'Feste Muster. Geduld, bis der Moment reif ist.',5),
('gate','6','Reibung','6️⃣',ARRAY['Konflikt','Intimität','Grenze'],'Der Grenz-Hüter emotionaler Intimität.',6),
('gate','7','Rolle des Selbst','7️⃣',ARRAY['Führung','Einfluss','Anerkennung'],'Die Rolle: wie du logisch führst.',7),
('gate','8','Beitrag','8️⃣',ARRAY['Individualität','Beispiel','Ausstrahlung'],'Das Individuum, das durch Beispiel beiträgt.',8),
('gate','9','Fokus','9️⃣',ARRAY['Details','Konzentration','Kleinigkeiten'],'Das Kleine. Fokus auf das, was zählt.',9),
('gate','10','Verhalten','🔟',ARRAY['Selbstliebe','Authentizität','Würde'],'Verhalten des Selbst. Liebe dich selbst.',10),
('gate','11','Ideen','1️⃣1️⃣',ARRAY['Konzepte','Frieden','Lehren'],'Ideen kommen und gehen. Harmoniebringer.',11),
('gate','12','Vorsicht','1️⃣2️⃣',ARRAY['Stille','Künstler','Timing'],'Die Stille als Ausdruckskraft.',12),
('gate','13','Zuhörer','1️⃣3️⃣',ARRAY['Erinnerung','Chronist','Zuhörer'],'Der Chronist des Lebens.',13),
('gate','14','Macht','1️⃣4️⃣',ARRAY['Reichtum','Durchhaltevermögen','Fülle'],'Macht durch Geduld und Fülle.',14),
('gate','15','Extreme','1️⃣5️⃣',ARRAY['Rhythmus','Vielfalt','Menschheit'],'Die Liebe zur Menschheit in ihren Extremen.',15),
('gate','16','Fähigkeiten','1️⃣6️⃣',ARRAY['Talent','Übung','Begeisterung'],'Enthusiasmus, der Fähigkeiten formt.',16),
('gate','17','Meinungen','1️⃣7️⃣',ARRAY['Logik','Führung','Zukunft'],'Meinungen, die sich als Muster herausstellen.',17),
('gate','18','Korrektur','1️⃣8️⃣',ARRAY['Kritik','Muster','Heilung'],'Was am Muster verbessert werden will.',18),
('gate','19','Wünsche','1️⃣9️⃣',ARRAY['Bedürfnis','Stamm','Berührung'],'Der Ruf nach Nähe und Ressourcen.',19),
('gate','20','Jetzt','2️⃣0️⃣',ARRAY['Gegenwart','Metamorphose','Handlung'],'Jetzt. Das unmittelbar Jetzt.',20),
('gate','21','Kontrolle','2️⃣1️⃣',ARRAY['Autonomie','Führung','Material'],'Kontrolle über die eigene Domäne.',21),
('gate','22','Offenheit','2️⃣2️⃣',ARRAY['Anmut','Kunst','Hingabe'],'Anmut. Offenheit für den emotionalen Moment.',22),
('gate','23','Assimilation','2️⃣3️⃣',ARRAY['Individualität','Erklären','Timing'],'Die Erkenntnis zur rechten Zeit teilen.',23),
('gate','24','Rationalisierung','2️⃣4️⃣',ARRAY['Rückblick','Wiederkehr','Verarbeitung'],'Das immer wieder Zurückkommen zu einem Thema.',24),
('gate','25','Geist des Selbst','2️⃣5️⃣',ARRAY['Unschuld','Liebe','Universum'],'Der Geist. Unschuldige universelle Liebe.',25),
('gate','26','Egoist','2️⃣6️⃣',ARRAY['Händler','Erinnerung','Übertragung'],'Das Ego-Gedächtnis. Der geschickte Übermittler.',26),
('gate','27','Fürsorge','2️⃣7️⃣',ARRAY['Nähren','Verantwortung','Stamm'],'Fürsorge für die, die dir anvertraut sind.',27),
('gate','28','Spieler','2️⃣8️⃣',ARRAY['Risiko','Sinn','Kampf'],'Das Spiel um den Sinn. Der Kämpfer.',28),
('gate','29','Hingabe','2️⃣9️⃣',ARRAY['Ja sagen','Engagement','Ausdauer'],'Die Kraft des Ja – sorgfältig gewählt.',29),
('gate','30','Gefühle','3️⃣0️⃣',ARRAY['Wünsche','Sehnsucht','Schicksal'],'Die feurigen Wünsche und Sehnsüchte.',30),
('gate','31','Einfluss','3️⃣1️⃣',ARRAY['Demokratie','Führung','Stimme'],'Einfluss durch demokratische Führung.',31),
('gate','32','Beständigkeit','3️⃣2️⃣',ARRAY['Dauer','Transformation','Klugheit'],'Was bleibt, wenn alles andere vergeht.',32),
('gate','33','Privatheit','3️⃣3️⃣',ARRAY['Rückzug','Erzählen','Reflexion'],'Rückzug, um das Geschehene zu erinnern.',33),
('gate','34','Kraft','3️⃣4️⃣',ARRAY['Macht','Beschäftigung','Selbstvertrauen'],'Pure Kraft. Aktivität aus Selbstvertrauen.',34),
('gate','35','Wandel','3️⃣5️⃣',ARRAY['Fortschritt','Erfahrung','Reise'],'Fortschritt durch Erfahrung. Sehnsucht nach Neuem.',35),
('gate','36','Krise','3️⃣6️⃣',ARRAY['Tiefe','Gefühl','Emotion'],'Die Dunkelheit des Gefühls – der Durchgang.',36),
('gate','37','Freundschaft','3️⃣7️⃣',ARRAY['Familie','Vereinbarung','Frieden'],'Der Handschlag. Familie durch Vereinbarung.',37),
('gate','38','Kämpfer','3️⃣8️⃣',ARRAY['Opposition','Sinn','Vision'],'Der Kampf für das, was Bedeutung hat.',38),
('gate','39','Provokation','3️⃣9️⃣',ARRAY['Hindernis','Geist','Auslöser'],'Der, der stört, um Geist freizusetzen.',39),
('gate','40','Alleinsein','4️⃣0️⃣',ARRAY['Befreiung','Wille','Grenze'],'Alleine. Die Befreiung der eigenen Willenskraft.',40),
('gate','41','Vorfreude','4️⃣1️⃣',ARRAY['Kontraktion','Fantasie','Beginn'],'Die Schwelle. Fantasie vor dem Beginn.',41),
('gate','42','Wachstum','4️⃣2️⃣',ARRAY['Zunahme','Abschluss','Zyklus'],'Zyklen abschließen, damit Neues wächst.',42),
('gate','43','Einsicht','4️⃣3️⃣',ARRAY['Durchbruch','Einzigartigkeit','Wissen'],'Der innere Durchbruch. Einsicht.',43),
('gate','44','Wachsamkeit','4️⃣4️⃣',ARRAY['Begegnung','Instinkt','Sinn'],'Der Instinkt für Menschen und Muster.',44),
('gate','45','König','4️⃣5️⃣',ARRAY['Sammler','Stamm','Führung'],'Der Sammler/die Königin des Stammes.',45),
('gate','46','Glück im Körper','4️⃣6️⃣',ARRAY['Liebe','Inkarnation','Glück'],'Die Liebe zum Körper – das große Geschenk.',46),
('gate','47','Erkenntnis','4️⃣7️⃣',ARRAY['Verwirklichung','Einsicht','Nachher'],'Das „Aha!" nach dem Durchdenken.',47),
('gate','48','Tiefe','4️⃣8️⃣',ARRAY['Brunnen','Weisheit','Unzulänglichkeit'],'Der Brunnen. Tiefe, die Weisheit gibt.',48),
('gate','49','Revolution','4️⃣9️⃣',ARRAY['Prinzipien','Rebellion','Reform'],'Umsturz, wenn Prinzipien verraten werden.',49),
('gate','50','Werte','5️⃣0️⃣',ARRAY['Gesetz','Verantwortung','Stamm'],'Die Wächterin der Stammes-Werte.',50),
('gate','51','Schock','5️⃣1️⃣',ARRAY['Wecken','Konkurrenz','Geist'],'Der Schock, der aufweckt.',51),
('gate','52','Stille','5️⃣2️⃣',ARRAY['Berg','Konzentration','Bewegungslosigkeit'],'Der Berg. Stille, die Kraft sammelt.',52),
('gate','53','Anfänge','5️⃣3️⃣',ARRAY['Entwicklung','Schritt','Druck'],'Druck zum Beginnen – Schritt für Schritt.',53),
('gate','54','Ambition','5️⃣4️⃣',ARRAY['Aufstieg','Ehrgeiz','Transformation'],'Der Aufstieg. Ehrgeiz mit Bodenhaftung.',54),
('gate','55','Überfluss','5️⃣5️⃣',ARRAY['Geist','Stimmung','Fülle'],'Überfluss des Geistes. Stimmungen als Tor.',55),
('gate','56','Erzähler','5️⃣6️⃣',ARRAY['Stimulation','Geschichten','Erfahrung'],'Der Geschichten-Erzähler des Lebens.',56),
('gate','57','Intuition','5️⃣7️⃣',ARRAY['Intuitive Klarheit','Sanftheit','Ohr'],'Die intuitive Klarheit im Ohr.',57),
('gate','58','Freude','5️⃣8️⃣',ARRAY['Vitalität','Kritik','Lebenslust'],'Die Freude, die korrigieren will.',58),
('gate','59','Sexualität','5️⃣9️⃣',ARRAY['Intimität','Zerstreuung','Fruchtbarkeit'],'Die Kraft der intimen Verbindung.',59),
('gate','60','Akzeptanz','6️⃣0️⃣',ARRAY['Begrenzung','Struktur','Evolution'],'Akzeptanz der Grenze, die Wandel ermöglicht.',60),
('gate','61','Geheimnis','6️⃣1️⃣',ARRAY['Innere Wahrheit','Mystik','Inspiration'],'Das Geheimnis, das inspiriert.',61),
('gate','62','Details','6️⃣2️⃣',ARRAY['Kleines','Expressionen','Fakten'],'Die Präzision der Details.',62),
('gate','63','Zweifel','6️⃣3️⃣',ARRAY['Vollendung','Frage','Logik'],'Der Zweifel, der nach Wahrheit fragt.',63),
('gate','64','Verwirrung','6️⃣4️⃣',ARRAY['Vor-Vollendung','Vergangenheit','Sinnsuche'],'Die reichhaltige Verwirrung vor der Klarheit.',64)

ON CONFLICT (category, key) DO UPDATE SET
  title      = EXCLUDED.title,
  emoji      = EXCLUDED.emoji,
  keywords   = EXCLUDED.keywords,
  short_text = EXCLUDED.short_text,
  sort_order = EXCLUDED.sort_order;
